Algoritmo "10"
// Disciplina   : Computação
// Professor   : Adriano Lages dos Santos
// Autor(a)    : Miguel Silva Pinheiro
// Data atual  : 07/03/2022
Var
pes, polegadas, jardas, milhas, res: real


Inicio

escreval("Digite o numero em pés:")
leia(pes)

polegadas <- pes * 12
jardas <- pes / 3
milhas <- jardas / 1760


escreval(pes," pés são:")
escreval(polegadas, " polegadas;")
escreval(jardas, " jardas;")
escreval(milhas, " milhas...")

Fimalgoritmo