Algoritmo "11"
// Disciplina   : Computação
// Professor   : Adriano Lages dos Santos
// Autor(a)    : Miguel Silva Pinheiro
// Data atual  : 07/03/2022
Var
nascimento, atual, res: real


Inicio

escreval("Digite o ano do seu nascimento:")
leia(nascimento)
escreval("Digite o ano atual:")
leia(atual)

escreval("Você tem entre", (atual - nascimento), " e", (atual - nascimento - 1), " anos!")
escreval("Em 2050 você terá aproximadamente", (2050 - nascimento), " anos")


Fimalgoritmo