Algoritmo "20"
// Disciplina   : Computação
// Professor   : Adriano Lages dos Santos
// Autor(a)    : Miguel Silva Pinheiro
// Data atual  : 07/03/2022
Var
custo, entrada: real


Inicio

escreval("Digite o custo do espetáculo:")
leia(custo)

escreval("Digite a entrada do espetáculo:")
leia(entrada)

escreval("Para alcançar o custo do espetáculo é preciso vender", int(custo / entrada + 0.5), " ingresos!")

Fimalgoritmo