Algoritmo "8"
// Disciplina   : Computação
// Professor   : Adriano Lages dos Santos
// Autor(a)    : Miguel Silva Pinheiro
// Data atual  : 07/03/2022
Var
numero, quadrado, cubo: real


Inicio

escreval("Digite o numero:")
leia(numero)

quadrado <- numero * numero
cubo <- quadrado * numero

escreval("O número ao quadrado é", quadrado)
escreval("O número ao cubo é", cubo)
escreval("A raiz quadrada é", raizq(numero))
escreval("A raiz cubica é", exp(numero, 1/3))


Fimalgoritmo