Algoritmo "9"
// Disciplina   : Computação
// Professor   : Adriano Lages dos Santos
// Autor(a)    : Miguel Silva Pinheiro
// Data atual  : 07/03/2022
Var
numero1, numero2, resultado: real


Inicio

escreval("Digite o primeiro numero (maior que 0):")
leia(numero1)
escreval("Digite o segundo numero:")
leia(numero2)

escreval("O numero", numero1, " elevado a", numero2, " é:", exp(numero1, numero2))


Fimalgoritmo